Remove version restriction from hdf5
during ilastik build I woudl get

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - iiboost -> hdf5 1.8.17.*
  - nifty -> hdf5 1.10.1.*
```